name: geo_tools
channels:
  - conda-forge

dependencies:
  # Python
  - python=3.12

  # Build essentials
  - cmake
  - ninja

  # Compiladores
  - gfortran
  - fortls
  - gcc
  - gxx
  - binutils

  # BLAS/LAPACK (asegura consistencia)
  - blas[build=openblas]
  - openblas
  - liblapack
  - libcblas

  # Numérico
  - armadillo
  - nlohmann_json
  - re2
  - pybind11
  - suitesparse
  - fftw

  # Geoespacial
  - gdal
  - geopandas
  - fiona

  # GMT
  - gmt
  - pygmt

  # Científico
  - numpy
  - scipy
  - pandas
  - matplotlib
  - meson
  - meson-python

  # UI
  - pyqt
  - google-re2

  # CUDA (opcional, comentar si no lo necesitas)
  - cuda-toolkit
